### PR TITLE
chore: updating node packages to latest (non-breaking) versions

### PR DESCRIPTION
**Pull request by jaredhill4**

### CODE REVIEW

**Comment by dwene** [comment]
@jaredhill4 if we do this, does that mean we'll need to update all dependencies that CLX has?

**Comment by jaruesink** [comment]
> @jaredhill4 if we do this, does that mean we'll need to update all dependencies that CLX has?

the only one I've had issues with is Formik, we might want to make sure CLX is always on the same Formik version.

**Review by jaruesink — APPROVED** [review]

**Comment by jaredhill4** [comment]
@dwene,

It doesn't seem like it. I tested the TSDX updates (which included the latest versions of the packages) in CLX, and everything seemed good for the most part.

To be sure, I will re-test once I've got a new version deployed (I'll probably start with a pre-release).

@jaruesink, I'll also double-check to make sure that Formik doesn't cause any problems. Any specific issues I should look out for?

**Comment by jaredhill4** [comment]
[](url)

**Pull request closed without merging**
